version: '3.5'

services:

  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    restart: always

  customer-api:
    image: customer-api
    build:
      context: .
      dockerfile: src/customer/Dockerfile
